FROM python:3.12-alpine3.22

RUN apk add --no-cache \
    build-base \
    curl \
    libffi-dev \
    openssl-dev \
    libpq-dev \
    postgresql

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

COPY pyproject.toml poetry.lock* ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-root --only main --no-interaction --no-ansi

EXPOSE 5000

COPY entrypoint.dev.sh /entrypoint.dev.sh
RUN chmod +x /entrypoint.dev.sh

ENV FLASK_APP=src/index.py
ENTRYPOINT ["/entrypoint.dev.sh"]