[tool.poetry]
name = "back"
version = "0.1.0"
description = ""
authors = ["tiaineno <olli.vj.tiainen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dotenv = "^0.9.9"
flask = "^3.1.2"
flask-cors = "^6.0.1"
requests = "^2.32.5"
loguru = "^0.7.3"
sqlalchemy = "^2.0.43"
flask-sqlalchemy = "^3.1.1"
psycopg2 = "^2.9.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
