"""changed amount to daily customer amount in customers table

Revision ID: 814062617edb
Revises: cea99e2e99c6
Create Date: 2025-12-01 08:36:20.269236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814062617edb'
down_revision = 'cea99e2e99c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_customer_amount', sa.Integer()))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('daily_customer_amount')

    # ### end Alembic commands ###
