"""drop item id column

Revision ID: 99ae3f10947d
Revises: 72f55e3ccaed
Create Date: 2025-11-20 13:16:22.188900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ae3f10947d'
down_revision = '72f55e3ccaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
