"""add not nullable to customer amount

Revision ID: d3f3a6be0760
Revises: 814062617edb
Create Date: 2025-12-01 08:38:10.940290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f3a6be0760'
down_revision = '814062617edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('daily_customer_amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('daily_customer_amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
