name: Build and push frontend image to Docker Hub

on:
  push:
    paths:
      - frontend/**
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: frontend
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/dtwin:frontend5
